import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MQTTProvider } from "@/context/MQTTContext"; // Asegúrate que el nombre sea correcto
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MQTTProvider>
          {children}
        </MQTTProvider>
      </body>
    </html>
  );
}
